# Generated by Django 3.2.5 on 2021-07-14 15:19

from django.db import migrations, models
import lead.models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='logo',
            field=models.ImageField(default='image/placeholder.jpeg', upload_to=lead.models.upload_to),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In progress'), ('lost', 'lost'), ('new', 'New'), ('contacted', 'Contacted'), ('won', 'won')], default='new', max_length=100),
        ),
    ]
