# Generated by Django 3.2.5 on 2021-07-14 20:02

from django.db import migrations, models
import django.db.models.deletion
import lead.models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20210714_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('won', 'won'), ('inprogress', 'In progress'), ('contacted', 'Contacted'), ('lost', 'lost'), ('new', 'New')], default='new', max_length=100),
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lead.models.upload_to, verbose_name='Image')),
                ('lead', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
            ],
        ),
    ]
