# Generated by Django 3.2.5 on 2021-07-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20210714_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('won', 'won'), ('new', 'New'), ('lost', 'lost'), ('inprogress', 'In progress'), ('contacted', 'Contacted')], default='new', max_length=100),
        ),
    ]
