# Generated by Django 3.2.5 on 2021-07-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_auto_20210717_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In progress'), ('lost', 'lost'), ('won', 'won'), ('contacted', 'Contacted'), ('new', 'New')], default='new', max_length=100),
        ),
    ]
